<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Responsable extends Model
{
    public $primaryKey = 'cod_trabajador';
    protected $table = 'rhuma_trabajador';

    protected $fillable = [
        'cod_trabajador',
        'cod_fotocheck',
        'dsc_apellido_paterno',
        'dsc_apellido_materno',
        'dsc_nombres',
        'fch_nacimiento',
        'flg_acceso_sistema',
        'fch_ingreso',
        'fch_salida',
        'flg_activo',
        'cod_tipo_documento',
        'dsc_documento',
        'dsc_direccion',
        'cod_pais',
        'cod_departamento',
        'cod_provincia',
        'cod_distrito',
        'dsc_mail',
        'dsc_telefono_1',
        'dsc_telefono_2',
        'dsc_ruta_foto',
        'fch_ingreso_planilla',
        'fch_salida_planilla',
        'cod_area',
        'cod_cargo',
        'cod_estado_civil',
        'num_hijos',
        'flg_grupo_sangre',
        'dsc_referencia',
        'cod_ubigeo',
        'cod_tipo_via',
        'dsc_calle_avenida',
        'dsc_nro_via',
        'dsc_dpto',
        'dsc_interior',
        'dsc_mza',
        'dsc_lote',
        'dsc_kilometro',
        'dsc_bloque',
        'dsc_etapa',
        'cod_tipo_zona',
        'dsc_urbanizacion',
        'dsc_contacto',
        'dsc_telefono_contacto_1',
        'dsc_telefono_contacto_2',
        'cod_pais_emisor',
        'cod_banco_deposito',
        'dsc_cuenta_bancaria_deposito',
        'cod_moneda_deposito',
        'cod_tipo_cuenta_deposito',
        'dsc_cuenta_interbancaria_deposito',
        'cod_banco_cts',
        'dsc_cuenta_bancaria_cts',
        'cod_moneda_cts',
        'cod_tipo_cuenta_cts',
        'dsc_cuenta_interbancaria_cts',
        'flg_tipo_pago',
        'flg_periocidad',
        'cod_larga_distancia',
        'cod_sexo',
        'cod_trabajador_interno',
        'cod_patron',
        'dsc_placa',
        'dsc_licencia',
        'dsc_marca',
        'dsc_modelo',
        'imp_prc_adelanto_quincena'
	];
}
